### PR TITLE
Fix a missing function name error

### PR DESCRIPTION
**Pull request by BrightTwikling**

### CODE REVIEW

**Comment by ralf979** [comment]
@BrightTwikling this is not the correct branch
why are you doing pr on something that doesn't work?

**Comment by BrightTwikling** [comment]
I don't consider that branch of u14 is correct branch as default branch.
Meanwhile, I knew that branch of u14 is latest branch by confirming the Network Graph on repository of manifest.
https://github.com/Black-Iron-Project/manifest/network

During the building by using branch of u14, the error occur on frameworks/base.
So I confirmed the commit relating source code nearby error occur,
I noticed that a missing function name makes the error occur.
Please refer to following commit that I confirmed.

https://github.com/Black-Iron-Project/frameworks_base/commit/12df3397d79cefc1ef30bcb292346fe8a235c62e

**Comment by BrightTwikling** [comment]
By fixing by using my PR, it became this error posion to work.

**Comment by ralf979** [comment]
@BrightTwikling Maybe you didn't understand. That's a dead, test branch... That no longer exists

**Comment by BrightTwikling** [comment]
Thank you so much for kind explanation. I understand it.

**Pull request closed without merging**
